Task3
potepancamp/keita_jyoshima pull request #9
Opened 2022-04-06 04:06 UTC by kyo1021

2022-04-06 12:17 UTC, tsakamo71 requested changes
レビュアーの坂本です。

コントローラーのテストが不足していますので、しっかりと書いてください。
そのほかインラインでコメントしましたのでご確認ください。

2022-04-06 12:17 UTC, tsakamo71 commented on app/views/potepan/products/_media_body.html.erb
> +    <% if @product.taxons.first.present? %>
パーシャルでインスタンス変数の参照はやめましょう

2022-04-06 12:17 UTC, tsakamo71 commented on spec/requests/potepan/categories_spec.rb
> +require 'rails_helper'
テストが不足しています。
コントローラーで実装した全ての仕様についてテストをしてください。

2022-04-06 12:42 UTC, kyo1021 commented on app/views/potepan/products/_media_body.html.erb
> +    <% if @product.taxons.first.present? %>
- [ ] fixed

2022-04-06 14:22 UTC, shimizzuu reviewed
レビュアーの清水です。
インラインでコメントしましたのでご確認ください。

2022-04-06 14:22 UTC, shimizzuu commented on app/controllers/potepan/categories_controller.rb
> +      @taxonomies = Spree::Taxonomy.includes(:taxons).all
`all`不要だと思います。

2022-04-06 14:22 UTC, shimizzuu commented on app/views/potepan/categories/_page_header.html.erb
> +          <h2><%= name %></h2>
nameだけだと何の名前か分からないので、具体的に命名した方が良いです。

2022-04-06 14:22 UTC, shimizzuu commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy2) { create(:taxonomy,name: "Brand")}
`!` は必要なものにだけ使用しましょう。

2022-04-06 15:30 UTC, kyo1021 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy2) { create(:taxonomy,name: "Brand")}
- [ ] fixed

2022-04-06 15:35 UTC, kyo1021 commented on app/controllers/potepan/categories_controller.rb
> +      @taxonomies = Spree::Taxonomy.includes(:taxons).all
- [ ] fixed

2022-04-06 15:36 UTC, kyo1021 commented on app/views/potepan/categories/_page_header.html.erb
> +          <h2><%= name %></h2>
- [ ] fixed

2022-04-06 15:53 UTC, kyo1021 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy2) { create(:taxonomy,name: "Brand")}
4・7行目の'let!'は表記を変えると、読み込みのタイミング的にローカル環境にてRspecを実行するとエラーになってしまうため、! を使用しております。
もしも、改善策ありましたらご教授いただけますと幸いです。

2022-04-06 16:48 UTC, kyo1021 commented
_page_header.html.erbのnameの命名
categories_controller.rbのallを削除しました。

確認お願いします。

2022-04-07 01:17 UTC, bary822 reviewed
レビュアーの福井です。概ね良さそうですがまだいくつか修正すべきところがあったのでコメントしました。
ご確認ください。

2022-04-07 01:17 UTC, bary822 commented on app/views/potepan/categories/show.html.erb
> +<%= render 'page_header', taxon: @taxon %>
partial内では`taxon.name`しか使っていないので、最初からそれだけを渡すようにしましょう。
情報のやり取りがシンプルになれば再利用性が向上します。

```suggestion
<%= render 'page_header', taxon_name: @taxon.name %>
```

2022-04-07 01:17 UTC, bary822 commented on spec/features/categories_spec.rb
> +      expect(page).to have_content taxon_2.products.count
`taxon`に紐づく商品数と`taxon_2`に紐づく商品数が同じ(1つずつ)なので、意図したテストになっていないのではないでしょうか。

2022-04-07 01:17 UTC, bary822 commented on spec/requests/potepan/categories_spec.rb
> +end
ファイル末尾に改行文字入れましょう。

2022-04-07 01:30 UTC, kyo1021 commented on spec/requests/potepan/categories_spec.rb
> +end
- [ ] fixed

2022-04-07 01:30 UTC, kyo1021 commented on app/views/potepan/categories/show.html.erb
> +<%= render 'page_header', taxon: @taxon %>
- [ ] fixed

2022-04-07 01:33 UTC, kyo1021 commented on spec/features/categories_spec.rb
> +      expect(page).to have_content taxon_2.products.count
- [ ] fixed

2022-04-07 02:02 UTC, kyo1021 commented
given(:product_3) { create(:product, taxons: [taxon_2], price: 30) }
を追加し、taxon_2のproductが2個になり、taxon_1と差別化を図りました。
変数名の変更、末尾改行を入れました

確認よろしくお願いします。

2022-04-07 03:50 UTC, kaizumoto approved these changes
レビュアーの伊豆本です。
私からはLGTMです。もう一名のレビューをお待ちください。

2022-04-07 12:08 UTC, nakanoTaku commented on spec/features/categories_spec.rb
> +  given(:product_3) { create(:product, taxons: [taxon_2], price: 30) }
テストで使ってないように見えるので、不要ならば削除しましょう。

2022-04-07 12:08 UTC, nakanoTaku commented on app/views/potepan/categories/_page_header.html.erb
> +          <li><a href="#">shop</a></li>
`link_to`使いましょう

2022-04-07 12:09 UTC, nakanoTaku commented
少しコメントしました！

2022-04-07 12:32 UTC, kyo1021 commented on app/views/potepan/categories/_page_header.html.erb
> +          <li><a href="#">shop</a></li>
自身が手を加えるファイルとして
_product_category.html.erbの29-33,40-43
_header.html.erbの8-9
_footer.html.erbの10-11にも同様の使われ方がされているhrefの分があるのですが、これも変更ですか？

さらに言えば、最初の段階から入っている複数のファイルにも同様の記述があるのですが、全て変更するのでしょうか？

2022-04-07 12:57 UTC, kyo1021 commented on spec/features/categories_spec.rb
> +  given(:product_3) { create(:product, taxons: [taxon_2], price: 30) }
ひとつ前のレビューにて
『taxonに紐づく商品数とtaxon_2に紐づく商品数が同じ(1つずつ)なので、意図したテストになっていないのではないでしょうか。』
とのレビューがあったため、taxon.products.countとtaxon_2.products.countの数に差別化を図るために使用しています。

2022-04-07 23:28 UTC, bary822 reviewed
レビュアーの福井です。一点だけコメントしました。
また、次回からcommit messageに意味のある情報を書くようにしましょう。チーム開発においては自分が行った変更を他の人がcommit単位で後から追いかけることが日常茶飯事です。

commit単体を他の人が見て、その変更意図や実現したかったことを詳細に書くようにしてください。
Web上にもcommit messageのお作法に関する記事が出ていると思うので、一度調べてみてください。

2022-04-07 23:28 UTC, bary822 commented on spec/features/categories_spec.rb
> +    create(:product, taxons: [taxon_2], price: 30)
ここでこの処理を行う理由が理解できませんでした。本来は`before`ブロックで行うことを意図していたのではないでしょうか。

2022-04-07 23:34 UTC, kyo1021 commented on spec/features/categories_spec.rb
> +    create(:product, taxons: [taxon_2], price: 30)
場所を間違えていました。
before内に移動しました

2022-04-08 02:42 UTC, hyo0306 reviewed
おつかれさまです！インラインでコメントしたので確認お願いします。また下記も確認お願いします↓
1. PRのタイトルと文言が適切ではないです。そのどのような機能のPRなのか、どのような実装をしたのかを説明するようにしてください。
2. コメントしたとおり対応漏れがあります。提出前に対応漏れがないか確認してから提出しましょう

2022-04-08 02:42 UTC, hyo0306 commented on spec/features/categories_spec.rb
> +      expect(page).to have_content taxon_2.products.count
bary822さんがおっしゃるように意図したテストになっていない可能性があります。
この場合は商品数を増やすでもいいですが、単純にチェックしたい項目の範囲をwithinで絞ることで解決できると思います

2022-04-08 02:42 UTC, hyo0306 commented on spec/features/products_spec.rb
> +      expect(page).to have_content product.description
beforeの中にexpectを入れた意図ってなんでしょうか？
そのページにアクセスできたかを調べたいということなら、visitできなければエラーが出ますし確認する必要ないですね

2022-04-08 02:42 UTC, hyo0306 commented on spec/requests/potepan/categories_spec.rb
> +
不要な空行

2022-04-08 02:42 UTC, hyo0306 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy) { create(:taxonomy,name: "Categories")}
}の前のスペース

2022-04-08 02:42 UTC, hyo0306 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy) { create(:taxonomy,name: "Categories")}
同様の箇所があるようなのでこのPRのファイルを全体的に確認してください

2022-04-08 02:42 UTC, hyo0306 commented on spec/features/categories_spec.rb
> +  given(:taxonomy_2) { create(:taxonomy) }
同じtaxonomyの中でtaxonが違えば表示される商品も変わるはずなので、taxonomyとrootは1つにしてその中でtaxonsを変える方式でも今回のテストは実現できると思います。必要以上にテストデータを作成している気がします

2022-04-08 11:38 UTC, kyo1021 commented on spec/features/products_spec.rb
> +      expect(page).to have_content product.description
features/products_spec.rbと見間違えてファイルの中身を移動させていましたので元に戻しました。

2022-04-08 11:39 UTC, kyo1021 commented on spec/features/categories_spec.rb
> +    create(:product, taxons: [taxon_2], price: 30)
- [ ] fixed

2022-04-08 11:44 UTC, kyo1021 commented on app/views/potepan/categories/_product_category.html.erb
> +                <% taxonomy.taxons.leaves.each do |leaf| %>
- [ ] fixed

2022-04-08 11:44 UTC, kyo1021 commented on app/views/potepan/categories/show.html.erb
> +            <% @taxon.leaves.each do |leaf| %>
- [ ] fixed

2022-04-08 11:44 UTC, kyo1021 commented on spec/features/products_spec.rb
> +      expect(page).to have_content product.description
- [ ] fixed

2022-04-08 11:44 UTC, kyo1021 commented on spec/requests/potepan/categories_spec.rb
> +
- [ ] fixed

2022-04-08 11:44 UTC, kyo1021 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy) { create(:taxonomy,name: "Categories")}
- [ ] fixed

2022-04-08 11:44 UTC, kyo1021 commented on spec/features/categories_spec.rb
> +  given(:taxonomy_2) { create(:taxonomy) }
- [ ] fixed

2022-04-09 01:43 UTC, shungo0525 requested changes
レビュアーの松村です。
コメントしたのでご確認ください。

修正されていない箇所があるので、Files changedを見て修正されているかご自身でも確認するようにしましょう。

2022-04-09 01:43 UTC, shungo0525 commented on app/controllers/application_controller.rb
> -
不要な差分ですね

2022-04-09 01:43 UTC, shungo0525 commented on spec/features/categories_spec.rb
> +    create(:product, taxons: [taxon_2], price: 30)
まだ残っています。

2022-04-09 01:43 UTC, shungo0525 commented on spec/features/products_spec.rb
> +      expect(page).to have_content product.description
こちらも変わっていないですね

2022-04-09 01:43 UTC, shungo0525 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy) { create(:taxonomy,name: "Categories") }
`,`のあとにスペースほしいですね

2022-04-09 01:43 UTC, shungo0525 commented on spec/requests/potepan/categories_spec.rb
> +require 'rails_helper'
コントローラーでは@taxon, @taxonomies, @productsを実装しているのでそれらを確認しましょう

2022-04-09 03:10 UTC, kyo1021 commented on spec/requests/potepan/categories_spec.rb
> +  let!(:taxonomy) { create(:taxonomy,name: "Categories") }
- [ ] fixed

2022-04-09 03:11 UTC, kyo1021 commented on spec/features/products_spec.rb
> +      expect(page).to have_content product.description
何度も申し訳ありません、修正いたしました。

2022-04-09 03:12 UTC, kyo1021 commented on spec/features/categories_spec.rb
> +    create(:product, taxons: [taxon_2], price: 30)
- [ ] fixed

2022-04-09 03:34 UTC, masanarih0ri reviewed
お疲れ様です。私からはLGTMです。続けてもう1人LGTMならマージ承認です。

2022-04-09 03:38 UTC, shungo0525 approved these changes
マージ承認です！
お疲れ様でした

2022-04-09 04:20 UTC, merged